app = "flask-pdf-db-rachit-1234"
primary_region = "bom"

[env]
  POSTGRES_DB = "pdf_manager"
  POSTGRES_USER = "rachit"
  PGDATA = "/var/lib/postgresql/data/pgdata"

[[mounts]]
  source = "pg_data"
  destination = "/var/lib/postgresql/data"

[[services]]
  internal_port = 5432
  protocol = "tcp"

[[services.ports]]
  port = 5432
